# Generated by Django 5.1.1 on 2024-10-05 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='review_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
