# Generated by Django 5.1.1 on 2024-10-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_cover',
        ),
    ]
