# Generated by Django 5.1.1 on 2024-10-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_api', '0003_review_user_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(default='Action', max_length=20),
        ),
    ]
