# Generated by Django 5.1.1 on 2024-10-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_api', '0004_movie_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
