# Generated by Django 5.1.1 on 2024-10-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_api', '0005_alter_movie_title_upload_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_upload_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
