# Generated by Django 5.1.1 on 2024-10-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_content_movies_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='user',
            new_name='Review_by',
        ),
    ]
